const esbuild = require('esbuild');
const path = require('path');

async function build() {
  console.log('Building frontend...');

  await esbuild.build({
    entryPoints: [path.join(__dirname, 'src', 'main.js')],
    bundle: true,
    outfile: path.join(__dirname, 'src', 'taskpane.bundle.js'),
    minify: true,
    sourcemap: true,
    target: ['chrome90'],
    format: 'iife',
    banner: {
      js: '// Auto-generated by esbuild. Do not edit manually.\n'
    }
  });

  console.log('Build complete: src/taskpane.bundle.js (+ .map)');
}

build().catch((err) => {
  console.error('Build failed:', err);
  process.exit(1);
});
